# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7558b7857e372c1cc533d15d4c523b1aea5d8ebafd5e58d11e5a3d38491485a4e990d4632a308be332838467cb739b4712b00ef040fc692700edae573b1e6f2

test:
  secret_key_base: 8a29caf378ecd144164044005c1bbdf017ca078e179c2b60d75bd09a33f0a038b9732a9c0666ae2edbf66dcec473b800a85ec8cd6cf8b670675c149b9f4992b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
